### ISSUE TITLE
Add into packagist

### ISSUE THREAD

**Issue by YannikFirre** [twistor/flysystem-http#1]
Hello,

I don't find this package on packagist ? is it ready to production ? 

Thanks :)

**Comment by jimmykane** [comment]
Yes please. Ping there! Anybody listening ? @twistor

**Comment by twistor** [comment]
I'm listening. It needs some work and more tests, but I should get to it next week.

**Comment by twistor** [comment]
This has moved over to https://github.com/twistor/flysystem-guzzle

twistor/flysystem-http is going to be used for something else.
